[package]
name = "generate_candid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uploader_canister = "0.1.1"
icgeek_candid_gen = "0.1.2"
candid = "0.8.3"

