[package]
name = "uploader_canister"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid_gen = { path = "../../../libraries/candid_gen" }
candid = "0.8.3"
serde = "1.0.146"
